# Generated by Django 5.0.1 on 2025-03-04 00:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="AddedUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=255, unique=True)),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                ("email", models.EmailField(blank=True, max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_users",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
