# Generated by Django 5.0.1 on 2025-04-03 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Foods",
            fields=[
                ("FoodID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Brand", models.CharField(max_length=255)),
                ("TypeofFood", models.CharField(max_length=50)),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ItemWeight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("ClassofFood", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Owners",
            fields=[
                ("OID", models.AutoField(primary_key=True, serialize=False)),
                ("LastName", models.CharField(max_length=255)),
                ("Street", models.CharField(max_length=255)),
                ("City", models.CharField(max_length=255)),
                ("ZipCode", models.CharField(max_length=10)),
                ("State", models.CharField(max_length=50)),
                ("Age", models.IntegerField()),
                ("AnnualIncome", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Pets",
            fields=[
                ("PetID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Age", models.IntegerField()),
                ("Street", models.CharField(max_length=255)),
                ("City", models.CharField(max_length=255)),
                ("ZipCode", models.CharField(max_length=10)),
                ("State", models.CharField(max_length=50)),
                ("TypeofPet", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.CreateModel(
            name="Owns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Year", models.IntegerField()),
                ("PetAgeatOwnership", models.IntegerField()),
                ("PricePaid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "OID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.owners"
                    ),
                ),
                (
                    "PetID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.pets"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TypeofFood", models.CharField(max_length=50)),
                (
                    "PetID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.pets"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Month", models.IntegerField()),
                ("Year", models.IntegerField()),
                ("Quantity", models.IntegerField()),
                (
                    "FoodID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.foods"
                    ),
                ),
                (
                    "OID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.owners"
                    ),
                ),
                (
                    "PetID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.pets"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AddedUser",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
